---
title: "Introduction to MSEApDbi and MSEAp.XXX.pb.db packages"
author:
- name: Atsushi Fukushima
  affiliation: RIKEN Center for Sustainable Resource Science
  email: afukushima@gmail.com
- name: Kozo Nishida
  affiliation: RIKEN Center for Biosystems Dynamics Research
  email: knishida@riken.jp
- name: Koki Tsuyuzaki
  affiliation: RIKEN Center for Biosystems Dynamics Research
  email: k.t.the-answer@hotmail.co.jp
date: "`r Sys.Date()`"  
output:
  BiocStyle::html_document
package: MSEApDbi
vignette: |
  %\VignetteIndexEntry{MSEApDbi}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---

# Introduction

MSEApDbi makes it easy to generate your own annotation package for MSEA.
The package design is the same as [MeSHDbi]() and [LRBaseDbi](), and the usage 
is the same.

This document provides the way to use LRBaseDbi and LRBase.XXX.eg.db-type
packages. LRBase.XXX.eg.db-type packages provide the pair list of ligand -
receptor genes. The packages are generated by the LRBaseDbi package. LRBaseDbi 
has two role; class-definition and the construction of LRBase.XXX.eg.db-type
packages. LRBaseDbi defines the class "LRBaseDb" and unify the objects’s 
behavior such as column function described later. The makeLRBasePackage 
function of LRBaseDbi generates the user’s original LRBase.XXX.eg.db-type
packages.

# References

1. Tsuyuzaki K, Morota G, Ishii M, Nakazato T, Miyazaki S, Nikaido I. MeSH ORA
framework: R/Bioconductor packages to support MeSH over-representation 
analysis. BMC bioinformatics. 2015 Dec;16(1):45.

# Session information {.unnumbered}

Here is the output of `sessionInfo()` on the system on which this
document was compiled:

```{r sessionInfo, echo=FALSE}
sessionInfo()
```